### ISSUE TITLE
handle release-upgrades (texlive 2012 -> 2013)

### ISSUE THREAD

**Issue by syphar** [Thermondo/heroku-buildpack-tex#1]

**Comment by syphar** [comment]
works currently by clearing the cache. 

Hardcoding the year won't be a solution to me. Of course the buildback will continue to work, but it will be an old version of texlive without any fixes. 

Happy to review and merge a PR if there is a good solution to this.

**Comment by xueye** [comment]
I'm new to the ruby stack and so I apologize if I misunderstood a step, however I cleared the cache as suggested and still am having this issue.

While trying to deploy, this is my .buildpacks file:

```
https://github.com/heroku/heroku-buildpack-ruby.git
https://github.com/perplexes/heroku-buildpack-clearcache
https://github.com/peterkeen/heroku-buildpack-vendorbinaries.git
https://github.com/Thermondo/heroku-buildpack-tex.git
```

For the vendorbinaries, I'm using the following vendor_urls to get pandoc:

```
https://s3.amazonaws.com/docverter-binaries/pandoc-1.12.0.2.tar.gz
https://s3.amazonaws.com/docverter-binaries/pandoc-templates-1.12.0.2.tar.gz
```

However, when I push to heroku I watch it remove the cache of all the gems and then get the following error:

```
remote: removed directory: ‘/app/tmp/cache/vendor’
remote: =====> Downloading Buildpack: https://github.com/peterkeen/heroku-buildpack-vendorbinaries.git
remote: =====> Detected Framework: VendorBinaries
remote: -----> Found a .vendor_urls file
remote:        Vendoring https://s3.amazonaws.com/docverter-binaries/pandoc-1.12.0.2.tar.gz
remote: =====> Downloading Buildpack: https://github.com/Thermondo/heroku-buildpack-tex.git
remote: =====> Detected Framework: TeX Live
remote: tlmgr: The TeX Live versions supported by the repository
remote:   (2013--2015)
remote: do not include the version of the local installation
remote:   (2012).
remote:  !     Push rejected, failed to compile Multipack app
remote:
remote: Verifying deploy....
remote:
remote: !	Push rejected to factotum.
remote:
```

Am I misunderstanding something here?

**Comment by syphar** [comment]
clearing the buildpack cache should be done only on the command line (see http://stackoverflow.com/questions/14368027/how-can-i-flush-the-heroku-buildpack-cache-dir) 

not in the .buildpacks file
