### ISSUE TITLE
Stuck on 2012

### ISSUE THREAD

**Issue by hassanshaikley** [Thermondo/heroku-buildpack-tex#13]
Stuck on version 2012. 

I am clearing the cache using https://github.com/perplexes/heroku-buildpack-clearcache.git

But no matter what TeXLive stays at 2012. : (

**Comment by codingjoe** [comment]
Hi @hassanshaikley 

Thanks for reaching out.
I just checked, we are using TeX Live 2016, with the same build pack. Maybe you should use [heroku's own tool](https://github.com/heroku/heroku-repo) to [purge your build cache](https://github.com/heroku/heroku-repo#purge_cache).

```
XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016)
kpathsea version 6.2.2
Copyright 2016 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 57.1; using 57.1
Compiled with zlib version 1.2.8; using 1.2.8
Compiled with FreeType2 version 2.6.3; using 2.6.3
Compiled with Graphite2 version 1.3.8; using 1.3.8
Compiled with HarfBuzz version 1.2.6; using 1.2.6
Compiled with libpng version 1.6.21; using 1.6.21
Compiled with poppler version 0.42.0
Compiled with fontconfig version 2.6.0; using 2.11.0
```

Let me know if it works!

**Comment by hassanshaikley** [comment]
Oh man! Yeah, the issue was the cache. I used a buildpack to clear the cache but it wasn't working. Turns out I needed to run a console command using a heroku plugin to clear the cache!
