### ISSUE TITLE
Trouble with fonts

### ISSUE THREAD

**Issue by sschloesser** [Thermondo/heroku-buildpack-tex#14]
I have been having trouble getting fonts to work with xelatex. I realize this isn't quite appropriate for a github issue but I didn't know where else to turn for help!

I've tried installing fonts by putting  `collection-fontsrecommended` in the texlive.profile and then using something like `\usepackage{palatino}`, which doesn't work. Basically the `\renewcommand\familydefault{\sfdefault}` doesn't seem to do anything because I'm still getting serif fonts. I also tried using fontspec, and `\setmainfont{}` but then I imagine specific font packages must be installed and I wasn't able to do it via tlmgr and placing more entries on the texlive.profile. Any ideas?

**Comment by codingjoe** [comment]
Hi @sschloesser do the font's work for you if you compile the PDF on your local machine?

**Comment by sschloesser** [comment]
Yes, both on my machine with the full texlive installation or on overleaf, the fonts work as expected, which is why I imagine some files might just be missing from the bare bones installation on heroku.

**Comment by syphar** [comment]
@sschloesser is this a TTF or LaTeX Font? 

- for latex font installing the corresponding package should be good enough. Perhaps you'll have to search inside your local (full) tex installation which package installs the font you need 
- if it's `xelatex` and a normal TTF font, they can't be installed via tex packages. You have to have them installed on your local system. In our case we have a `.fonts` directory in our application repo, the fonts there get picked up by heroku/xelatex

**Comment by sschloesser** [comment]
Ok so including the TTF font in .fonts and using it via 
`\usepackage{fontspec}
\setmainfont{Arial}`
worked! The only thing that is still not working is bold via `\textbf{bold text here}`. Could that be a deficiency of the TTF file I used?

**Comment by sschloesser** [comment]
Problem solved! I wasn't aware that different .ttf files were necessary for each font type. Thanks for the help!
