### ISSUE TITLE
Custom TeX live version  - No access to cryptographic signature

### ISSUE THREAD

**Issue by pckapps** [Thermondo/heroku-buildpack-tex#22]
I've selected custom TeX Live version by adding a file called texlive.repository with the following content:
ftp://tug.org/historic/systems/texlive/2017/tlnet-final/

When I build my Heroku app I get the following error:

remote: tlmgr: main database at ftp://tug.org/historic/systems/texlive/2017/tlnet-final/ is not signed: no access to cryptographic signature
remote:  !     Push rejected, failed to compile TeX Live app.

Anybody knows how this can be fixed?

**Comment by amureki** [comment]
Hi @pckapps !

Could you, please, try to use the next repository:
http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2017/tlnet-final

It is the one that is being maintained by university of Utah and seems to be stable to me.

**Comment by pckapps** [comment]
Thanks! That worked! I think I should just download this myself and save it on S3. Do you know which files are required or do I need all of them?

**Comment by amureki** [comment]
@pckapps great that it helped!
Sadly, I did not dig deeply into the minimal required packages there and cannot tell you what could be cherry picked from there. :(
Theoretically you won't need windows executables and maybe updateables as well.

**Comment by sschloesser** [comment]
@pckapps I would be really interested in hearing how the cloning to S3 worked if you ended up doing that.

**Comment by pckapps** [comment]
Yes it did. Just need to clear your Heroku build cache and don't append a slash to the url of your S3 bucket
